apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  params:
   - name : name
     
  tasks:
    - name: hello
      taskRef:
        name: hello-world

      params: 
       - name: name
         value: "$(params.name)"

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
    - name: branch
      default: master 
     
  tasks:
    - name: clone
      taskRef:
        name: checkout
      params: 
        - name: repo-url
          value: "$(params.repo-url)"
        - name: branch
          value: "$(params.branch)"
      
    - name: lint
      taskRef:
        name: hello-world
      params:
        - name: name
          value: "Calling Flake8 linter..."
      runAfter:
        - clone
    
    - name: tests
      taskRef:
        name: hello-world
      params:
        - name: name
          value: "Running unit tests with PyUnit..."
      runAfter:
        - lint
    
    - name: build
      taskRef:
        name: hello-world
      params:
        - name: name
          value: "Building image for $(params.repo-url) ..."
      runAfter:
        - tests
    
    - name: deploy
      taskRef:
        name: hello-world
      params:
        - name: name
          value: "Deploying $(params.branch) branch of $(params.repo-url) ..."
      runAfter:
        - build